### ISSUE TITLE
No matching distribution found for pyrilog

### ISSUE THREAD

**Issue by ghaithcode** [xbili/pyrilog#1]
Hello, 

I am trying to install pyrilog. Can you please help with the following error: 

_Collecting pyrilog
  Could not find a version that satisfies the requirement pyrilog (from versions: )
No matching distribution found for pyrilog_

Thanks,

Ghaith

**Comment by xbili** [comment]
Oh I'm so sorry, I took this down from `PyPi`. I should probably update the `README` for that.

You can still run the project by first cloning this repository and running:

`python -m pyrilog <args>`

Cheers!

**Comment by ghaithcode** [comment]
Thank you for your reply. I tried to apply the following:

python -m pyrilog --size <size> --width <width> --with-pipeline

as follows:

python -m pyrilog --size 32 --width 32 

I get the following error: 

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users../pyrilog-master/pyrilog/__main__.py", line 1, in <module>
    import click
ImportError: No module named click
 
I am not sure if the error is in the code or my use. Can you please guide me with an example how to run to run it.

Thanks again,

**Comment by xbili** [comment]
@ghaithcode You would have to run `pip install -r requirements.txt` before usage.
